name: iosmovie
options:
  bundleIdPrefix: com.iosmovie
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
targets:
  iosmovie:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iosmovie
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iosmovie.app
        PRODUCT_NAME: 影视王
        INFOPLIST_FILE: iosmovie/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "5.0"
        SWIFT_OBJC_BRIDGING_HEADER: iosmovie/iosmovie-Bridging-Header.h
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0"
        ENABLE_PREVIEWS: NO